@startuml
skinparam nodesep 80
() "verde 000\nbaseline 001" as v0b1
() "baseline 000" as b0
() "baseline 002" as b2
() "baseline 003" as b3
() "baseline 004" as b4
() "baseline 005" as b5

() "verde 001\nbaseline 009" as v0b9
() "baseline 006" as b6

() "verde 002\nbaseline 015" as vnbm

v0b1 -r-> b0
b0 -r-> b2
b2 -r-> b3
b3 -r-> b4
b4 -r-> b5

v0b1 -d-> v0b9
v0b9 -r..-> b6
v0b9 -d.-> vnbm

note top of v0b1
The most effective group
of visualisations uses the x,y
and size channels. This vis is
presented first because we are
confident in the causal relationships
between the query fields across all
three channels. The lowest strength
field encodes the least precise
channel (size).
end note

note top of b0
This vis may be preferable
because quality of life has
high cardinality so may be better
suited to a positional channel.
The x and y encodings preserve
causal relationships.
end note

note bottom of b2
The x and y channels
are swapped...
end note

note left of v0b9
The second most effective
group encodes the colour
channel instead of the
size channel. This vis is
presented first because we are
confident in the causal
relationships between the
query fields across all
three channels. The lowest
strength field encodes the
least precise channel (colour).
end note


@enduml